apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: my-namespace
spec:
  encryptedData:
    password: AgB8jAuqXaw5AFKVUAWneM0IDt6xB+csNmim1u/ACsRXTXw6t1u2Pb2UbgVawTbdhPyidMpGWBTie4p/t05diZiTqDC7s2teeCU4nWXCMsuWvAAHl0NI0F2bqBPXoTZG+FNsSlItmnNawJmt0a1ipD72INurdTn6G9kl1fPLxDgrQaTxJNkayY7AW9uq6soc3ojOTxtB/Kj24chqMVbJWrkwX20l1Ubrb0/UiWW2rp1uisQdOJW6H6uFDQ0fixltJVPbR1uF6EXhbp4qZi+fgGJd6ya1hu3x816U3POtUioW3bML1K82pEzeJnoSxbYIaS4hP/aMTXYX6Jwcs6cCUUwl5HyTx+go8CxiS/o89cNQkS/HtckTl7e8oURfIFR8WjIoAKkzYsyQ5ago1tBW2oZLzuW1s99wciFM6GTRumJDvsOVxeDpam/m70NTTFQARS/HbVjIfo+RkE8Et8jNsFJHJhVzHGGieuZYmkrARtqwmU2278iwCi37rqRGIADX5Ps+pCWIWnZ47Hw94AHuAs2/1XYeKb6MNbh7xP1zZDuOOmYfACwxOJ5Pt6I6gvhr2mvuyrGf23oPbHv739XufQg7gbKjmg08RWzPlBcedzDbfxuxk8MCrrWfEd+DoOTkKQ1zPnSnDb7QoP9XKofbXVRSAlwb/fkdmHY3c7SCGUyebCkmQQiDww7OM3EhwCYwt+GH6pa8Vg==
    username: AgAb+vIIOKaPEEUd59JRFH16HzRFkBPiXLKryBNcvfWLJHsnWGt4ZPrINuqtnG/OM6B23htF8EKVRpZgAk7u2udz5FHFyYAHTj1vRi1/PxWry7pshoiu/bjsys/vZ7UIWUBYq36c1SWK+NpAh/92R9Kcs53msgeeWhjYzoFxtynlmbU5y9r7I+gfx73olqRAt5DTFonfYw2zJAAV50NEpOObuqqCSaLVit8o9t/XLWuloqju//bj4znQoIzHFw7UJzr9HZn+DMcOOGyeyOa+4XwhF5gAnoZSC6ryzyPrsSUf7SNQoM/jY28D04ip+yZ2w+R3SxHPI79aW4K4mddwOaoRNoLldvriwl8/MdyddcS3w3aYBzgO03YzXWau6LJ3Va35Kjov+nqFANQ+Pj3wy89HduEKX+RFGLFLJgMFOWtdbsEzJmKnUiguzutbt8mzOKd1uCO/XAyGHtF8NafD8n84Eg88Vl10LftBvtV9Lp3UJV7UJ8ppaMLOT6szi1rh1Ay2rIUdyOVkcyFkdPlXzvJVbBm9H2M+RAsNwk7ybqj/cRdrlDlWS+wNhxB2HQE3524kYqr8A1LdJs1uLPnTcd6R799zquqhLDRBfVuagP11FV03FRwPU0+fAunWS94iEOr906l9qJC2j6QkMRqujNINNH88PrUKSYemV7J1u4VIytu12IuHr7GEksujK9WZpK8M3o6vTnUerDo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: my-namespace

